### ISSUE TITLE
Last sent code for automated library tests

### ISSUE THREAD

**Issue by jacob-ebey** [digitimate/digitimate#10]
## Proposal

Implement a way to retrieve the last code sent to a mobile number so automated testing of clients can be performed.
## Changes to sendCode

Add a boolean parameter called `getCode` that would send the code back in the response.
A new response would look like so:

``` json
{
    "userMobileNumber": "5555555555",
    "err": null,
    "code": 666666
}
```

where '666666' is the code sent to the users mobile number.

**Comment by ide** [comment]
We might want to add the notion of "testing mode" so it's clear that production apps should never have access to the code. I emailed Twilio support to see if they support dry runs with their API since it'd be nice for the test to be E2E.

**Comment by jacob-ebey** [comment]
That would be great. I would like to get the testing setup within the next day or so as I am using this to learn about CI/Automated build machines as well.

**Comment by ide** [comment]
Yeah, this would let us move to continuous deployment as well.

**Comment by ide** [comment]
@jacob-ebey after the new server is deployed, you will be able to add the `__testing__` query param and sendCode will respond like:

`{"userMobileNumber":"1112223333","__testing__":{"code":"624240"},"err":null}`

Likewise to check the code, just add the `__testing__` param to your checkCode request.

**Comment by jacob-ebey** [comment]
Can you ping me here when the new deploy is done?

**Comment by ide** [comment]
@jacob-ebey: the server has been updated
