### ISSUE TITLE
DigitimateSharp - The easy to use C# client

### ISSUE THREAD

**Issue by jacob-ebey** [digitimate/digitimate#5]
I liked the idea here and thought I may want to use it in the future so I wrote a C# client for this.

It can be found here: https://github.com/jacob-ebey/DigitimateSharp

This is UNTESTED! It is simple so it should be good to go but no promises.

Please fork on your profile / link on your site so your users can have easy access to it.

It is also available on NuGet at https://www.nuget.org/packages/DigitimateSharp.

**Comment by ccheever** [comment]
I listed and linked to DigitimateSharp from the homepage now.
http://digitimate.com/

Feel free to send a pull request if you want expanded documentation or to change the way it's described, etc.

Closing this for now! Thanks!
